site_name: My Flask webapp Docs
theme:
    name: "material"
plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import sys
                    - print('running inside code')
                    - sys.path.append(r'..\src')
                rendering:
                    show_source: true  
